---
title: "BootstrapAnalysis"
author: "Koen Bresters"
date: "2023-03-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Import files

```{r}
source("monster_functie.r")
```

First we set some global parameters.

```{r}
N = 2000
true_variance_N = 10000
M = 2000
alphas = c(0.005, 0.01, 0.05, 0.1)
```

Now we we define the distributions and estimators that we will use.

```{r}
sd1norm <- function (x) function(N) rnorm(N, mean=x, sd=1)
norm <- function (x) function(N) rnorm(N, mean=x$mean, sd=x$sd)
norm_full_estimator <- function(x) list(mean=mean(x), sd=sd(x))
norm_mean_estimator <- function(x) mean(x)
norm_sd_estimator <- function(x) sd(x)

gamma <- function(x) function(N) rgamma(N, x$shape, shape=x$scale)
gamma_full_estimator <- function(x){
  E = mean(x)
  V = var(x)
  list(shape=E^2/V, scale=V/E)
}
gamma_shape_estimator <- function(x) mean(x)^2/var(x)

cauchy <- function(x) function(N) rcauchy(N, location=x$loc, scale=x$scale)
cauchy_full_estimator <- function(x) list(loc=median(x), scale=IQR(x)/2)
cauchy_loc_estimator <- function(x) median(x)

uniform <- function(x) function(N) runif(N, max=x)
uniform_estimator <- function(x) max(x)*(1+1/length(x))

exponential <- function(x) function(N) rexp(N, rate=x)
exponential_estimator <- function(x) (length(x)-2)/sum(x)

poisson <- function(x) function(N) rpois(N, lambda=x)
poisson_estimator <- function(x) mean(x)

```

Set the parametric tests that we want to do.

```{r}
param_tests = list()
# tests on the effect of n and the distribution and parametric vs non-parametric
for (n in c(10, 50, 200, 1000)){
  param_tests = append(param_tests, list(
    list(
      test_name="normal distr. with sd 1, estimating mean", 
      true_distr_gen=sd1norm, 
      true_params=0,
      true_theta=0, 
      fake_distr_gen=sd1norm,
      full_estimator=norm_mean_estimator, 
      estimator=norm_mean_estimator, 
      n=n
    ),
    list(
      test_name="normal distr. with unknown sd, estimating mean", 
      true_distr_gen=norm, 
      true_params=list(mean=0, sd=1),
      true_theta=0,
      fake_distr_gen=norm,
      full_estimator=norm_full_estimator, 
      estimator=norm_mean_estimator, 
      n=n
    ),
    list(
      test_name="uniform, estimating maximum", 
      true_distr_gen=uniform, 
      true_params=1,
      true_theta=1, 
      fake_distr_gen=uniform,
      full_estimator=uniform_estimator, 
      estimator=uniform_estimator, 
      n=n
    ),
    list(
      test_name="cauchy, estimating location", 
      true_distr_gen=cauchy, 
      true_params=list(locaion=0,scale=1),
      true_theta=0,
      fake_distr_gen=cauchy,
      full_estimator=cauchy_full_estimator, 
      estimator=cauchy_loc_estimator, 
      n=n
    ),
    list(
      test_name="exponential, estimating rate", 
      true_distr_gen=exponential, 
      true_params=1,
      true_theta=1,
      fake_distr_gen=exponential,
      full_estimator=exponential_estimator, 
      estimator=exponential_estimator, 
      n=n
    ),
    list(
      test_name="poisson, estimating lambda", 
      true_distr_gen=poisson, 
      true_params=1,
      true_theta=1,
      fake_distr_gen=poisson,
      full_estimator=poisson_estimator, 
      estimator=poisson_estimator, 
      n=n
    )
  ))
}

# robustness tests
param_tests = append(param_tests, list(
    list(
      test_name="cauchy thinking it is normal, estimating location", 
      true_distr_gen=cauchy, 
      true_params=list(locaion=0,scale=1),
      true_theta=0, 
      fake_distr_gen=norm,
      full_estimator=norm_full_estimator, 
      estimator=norm_mean_estimator, 
      n=200
    ),
    list(
      test_name="exponential thinking it is normal, estimating rate", 
      true_distr_gen=exponential, 
      true_params=1,
      true_theta=1, 
      fake_distr_gen=norm,
      full_estimator=norm_full_estimator, 
      estimator=norm_mean_estimator, 
      n=200
    )
))


```

Set the non-parametric tests that we want to do.

```{r}
nonparam_tests =list()
for (n in c(10, 50, 200, 1000)){
  nonparam_tests <- append(nonparam_tests, list(
    list(
      test_name="normal distr., estimating mean",
      true_distr=norm(list(mean=0,sd=1)),
      estimator=norm_mean_estimator,
      true_theta=0,
      n=n
    ),
    list(
      test_name="uniform, estimating maximum", 
      true_distr=uniform(1), 
      true_theta=1,
      estimator=uniform_estimator, 
      n=n
    ),
    list(
      test_name="cauchy, estimating location", 
      true_distr=cauchy(list(loc=0, scale=1)), 
      true_theta=0,
      estimator=cauchy_loc_estimator, 
      n=n
    ),
    list(
      test_name="exponential, estimating rate", 
      true_distr=exponential(1), 
      true_theta=1,
      estimator=exponential_estimator, 
      n=n
    ),
    list(
      test_name="poisson, estimating lambda", 
      true_distr=poisson(1),
      true_theta=1,
      estimator=poisson_estimator, 
      n=n
    )
  ))
}
```

Run the tests.

```{r}
results_list = list()

# parametric tests
for (x in param_tests){
  full_name = paste(x$test_name, ", parametric", ", n=", format(round(x$n, digits=0), nsmall=0), sep="")
  print(paste("calculating ", full_name, "...", sep=""))
  monster_results = param_monster(x$true_distr_gen, x$true_params, x$true_theta, x$full_estimator, x$n, M, N, true_variance_N, alphas,
                                  x$estimator, x$fake_distr_gen)
  results_list <- append(results_list, list(append(list(test=full_name), monster_results)))
}

# non-parametric tests
for (x in nonparam_tests){
  full_name = paste(x$test_name, ", non-parametric", ", n=", format(round(x$n, digits=0), nsmall=0), sep="")
  print(paste("calculating ", full_name, "...", sep=""))
  monster_results = nonparam_monster(x$true_distr, x$estimator, x$true_theta, x$n, M, N, true_variance_N, alphas)
  results_list <- append(results_list, list(append(list(test=full_name), monster_results)))
}

result_table = do.call(rbind.data.frame, results_list)
result_table
```






