---
title: "Modelleren: statistiekproject"
date: '2023-02-23'
output: pdf_document
---

```{r}
rm(list = ls())
```

## Part 2: data analysis

source("confidence_intervals.r")

stderror <- function(x) sd(x)/sqrt(length(x))

bootstrap_sderror <- rep(0, 10000)

2018:
P: mannen + vrouwen, >= 70 jaar
I: aspirine
C: placebo 
O: hartaandoening ontwikkeld

1988:
P: mannelijke artsen, 40-84 jaar
I: aspirine
C: placebo
O: hartaandoening ontwikkeld

```{r}
risk_ratio <- function(sample) {
  mean(sample[1])/mean(sample[2])
}

BCa <- function(bootstrap_estimates, bootstrap_sderrors, theta_hat, start_sample, sample_sderror, estimator, alpha) {
  B <- length(bootstrap_estimates)
  N <- length(start_sample)
  number <- 0
  # x <- list(sample)
  theta <- rep(0, N)
  
  for(i in 1:B){
    if (bootstrap_estimates[i] < theta_hat){
      number <- number + 1
    }
  }
  
  if (number == 0)
    z0 <- -10
  else if (number == B)
    z0 <- 10
  else
    z0 <- qnorm(number/B)
  
  for(i in 1:N)
  {
    x_i <- start_sample[-i]
    theta[i] <- estimator(x_i)
  }
  
  theta_mean <- mean(theta)
  
  teller <- (theta_mean - theta)^3
  noemer <- (theta_mean - theta)^2
  
  a <- sum(teller)/(6*sum(noemer)^(3/2))
  
  alpha_1 <- pnorm(z0 + (z0 + qnorm(alpha/2))/(1 - a*(z0 + qnorm(alpha/2))))
  alpha_2 <- pnorm(z0 + (z0 + qnorm(1-alpha/2))/(1 - a*(z0 + qnorm(1-alpha/2))))
  
  bootstrap_estimates <- sort(bootstrap_estimates)
  
  theta_lo <- bootstrap_estimates[ceiling(B * alpha_1)]
  theta_up <- bootstrap_estimates[floor(B * alpha_2)]
  
  CI <- c(theta_lo, theta_up)
  
  return(CI)
}

Bootstrap_t <- function(bootstrap_estimates, bootstrap_sderrors, theta_hat, sample_sderror, alpha) {
  B <- length(bootstrap_estimates)
  Z <- rep(0, B)
  
  for(i in 1:B)
    Z[i] <- (bootstrap_estimates[i]-theta_hat)/bootstrap_sderrors[i]
  
  Z <- sort(Z)
  
  h1 <- ceiling(B * alpha/2)
  h2 <- floor(B * (1-alpha/2))
  
  t1 <- Z[h1]
  t2 <- Z[h2]
  
  theta_lo <- theta_hat-t2*sample_sderror
  theta_up <- theta_hat-t1*sample_sderror
  
  CI <- c(theta_lo, theta_up)
  
  return(CI)
}   


Basic <- function(bootstrap_estimates, bootstrap_sderrors, theta_hat, sample_sderror, alpha) {
  B <- length(bootstrap_estimates)
  
  h1 <- ceiling(B * alpha/2)
  h2 <- floor(B * (1-alpha/2))
  
  bootstrap_estimates = sort(bootstrap_estimates)
  
  theta_lo <- bootstrap_estimates[h1]
  theta_up <- bootstrap_estimates[h2]
  
  CI <- c(theta_lo, theta_up)
  
  return(CI)
}

# set parameters

N = 10000

## 2018 trial
N_asp_2018 = 9525
n_asp_2018 = 448
N_plac_2018 = 9589
n_plac_2018 = 474

## 1988 trial
N_asp_1988 = 11037
n_asp_hart_1988 = 104
n_asp_hersen_1988 = 80
N_plac_1988 = 11034
n_plac_hart_1988 = 189
n_plac_hersen_1988 = 70

# relative risk 
r_asp_2018 <- n_asp_2018/N_asp_2018
r_plac_2018 <- n_plac_2018/N_plac_2018
(RR_2018 <- r_asp_2018/r_plac_2018)
r_asp_hart_1988 <- n_asp_hart_1988/N_asp_1988
r_plac_hart_1988 <- n_plac_hart_1988/N_plac_1988
(RR_hart_1988 <- r_asp_hart_1988/r_plac_hart_1988)
r_asp_hersen_1988 <- n_asp_hersen_1988/N_asp_1988
r_plac_hersen_1988 <- n_plac_hersen_1988/N_plac_1988
(RR_hersen_1988 <- r_asp_hersen_1988/r_plac_hersen_1988)

# make vectors with zeros and ones
asp_2018 <- c(rep(0, N_asp_2018-n_asp_2018), rep(1, n_asp_2018))
plac_2018 <- c(rep(0, N_plac_2018-n_plac_2018), rep(1, n_plac_2018))

asp_hart_1988 <- c(rep(0, N_asp_1988-n_asp_hart_1988), rep(1, n_asp_hart_1988))
plac_hart_1988 <- c(rep(0, N_plac_1988-n_plac_hart_1988), rep(1, n_plac_hart_1988))

asp_hersen_1988 <- c(rep(0, N_asp_1988-n_asp_hersen_1988), rep(1, n_asp_hersen_1988))
plac_hersen_1988 <- c(rep(0, N_plac_1988-n_plac_hersen_1988), rep(1, n_plac_hersen_1988))

# calculate estimators of bootstraps
bootstrap_est_2018 <- replicate(N, expr = {
  sample_asp <- sample(asp_2018, replace = T)
  sample_plac <- sample(plac_2018, replace = T)
  mean(sample_asp)/mean(sample_plac)
})

bootstrap_est_hart_1998 <- replicate(N, expr = {
  sample_asp <- sample(asp_hart_1988, replace = T)
  sample_plac <- sample(plac_hart_1988, replace = T)
  mean(sample_asp)/mean(sample_plac)
})

bootstrap_est_hersen_1998 <- replicate(N, expr = {
  sample_asp <- sample(asp_hersen_1988, replace = T)
  sample_plac <- sample(plac_hersen_1988, replace = T)
  mean(sample_asp)/mean(sample_plac)
})

#calculate standard error of bootstraps
bootstrap_sderror_2018 <- replicate(N, expr = {
  sample_asp <- sample(asp_2018, replace = T)
  sample_plac <- sample(plac_2018, replace = T)
  ones_asp <- sum(sample_asp)
  ones_plac <- sum(sample_plac)
  sqrt(1/ones_asp + 1/ones_plac -1/N_asp_2018 - 1/N_plac_2018)
})

bootstrap_sderror_hart_1988 <- replicate(N, expr = {
  sample_asp <- sample(asp_hart_1988, replace = T)
  sample_plac <- sample(plac_hart_1988, replace = T)
  ones_asp <- sum(sample_asp)
  ones_plac <- sum(sample_plac)
  sqrt(1/ones_asp + 1/ones_plac -1/N_asp_1988 - 1/N_plac_1988)
})

bootstrap_sderror_hersen_1988 <- replicate(N, expr = {
  sample_asp <- sample(asp_hersen_1988, replace = T)
  sample_plac <- sample(plac_hersen_1988, replace = T)
  ones_asp <- sum(sample_asp)
  ones_plac <- sum(sample_plac)
  sqrt(1/ones_asp + 1/ones_plac -1/N_asp_1988 - 1/N_plac_1988)
})

# put start sample in vector
start_sample_2018 <- c(asp_2018, plac_2018)
start_sample_hart_1988 <- c(asp_hart_1988, plac_hart_1988)
start_sample_hersen_1988 <- c(asp_hersen_1988, plac_hersen_1988)

# calculate standard error of original sample
sample_stderror_2018 <- sqrt(1/n_asp_2018 + 1/n_plac_2018 -1/N_asp_2018 - 1/N_plac_2018)
sample_stderror_hart_1988 <- sqrt(1/n_asp_hart_1988 + 1/n_plac_hart_1988 -1/N_asp_1988 - 1/N_plac_1988)
sample_stderror_hersen_1988 <- sqrt(1/n_asp_hersen_1988 + 1/n_plac_hersen_1988 -1/N_asp_1988 - 1/N_plac_1988)

#BCa_2018 <- BCa()
Bootstrap_t_2018 <- Bootstrap_t(bootstrap_est_2018, bootstrap_sderror_2018, RR_2018, sample_stderror_2018, 0.05)
Basic_2018 <- Basic(bootstrap_est_2018, bootstrap_sderror_2018, RR_2018, sample_stderror_2018, 0.05)

#BCa_hart_1988 <- BCa()
Bootstrap_t_hart_1988 <- Bootstrap_t(bootstrap_est_hart_1998, bootstrap_sderror_hart_1988, RR_hart_1988, sample_stderror_hart_1988, 0.05)
Basic_hart_1988 <- Basic(bootstrap_est_hart_1998, bootstrap_sderror_hart_1988, RR_hart_1988, sample_stderror_hart_1988, 0.05)

#BCa_hersen_1988 <- BCa()
Bootstrap_t_hersen_1988 <- Bootstrap_t(bootstrap_est_hersen_1998, bootstrap_sderror_hersen_1988, RR_hersen_1988, sample_stderror_hersen_1988, 0.05)
Basic_hersen_1988 <- Basic(bootstrap_est_hersen_1998, bootstrap_sderror_hersen_1988, RR_hersen_1988, sample_stderror_hersen_1988, 0.05)




```
