---
title: "Distributions"
date: '2023-03-22'
output: pdf_document
---

With this document, the probability density/mass functions of five distributions have been visualized. 

```{r}
# clear environment 
rm(list = ls())

# load needed packages
library(ggplot2)

# create colour vector 
colourvector <-c("Black", "Orange", "Sky blue", "Green")
```

# Normal distribution
```{r}
ggplot(data.frame(x = c(-8, 8)), aes(x = x)) +
  stat_function(aes(colour = "mean = 0, sd = 1",
                    linetype = "mean = 0, sd = 1"),
                fun = dnorm,
                args = list(mean = 0, sd = 1)) +
  stat_function(aes(colour = "mean = 0, sd = 3",
                    linetype = "mean = 0, sd = 3"),
                fun = dnorm,
                args = list(mean = 0, sd = 3)) +
  stat_function(aes(colour = "mean = -2, sd = 2",
                    linetype = "mean = -2, sd = 2"),
                fun = dnorm,
                args = list(mean = -2, sd = 2)) +
  stat_function(aes(colour = "mean = 2, sd = 1",
                    linetype = "mean = 2, sd = 1"),
                fun = dnorm,
                args = list(mean = 2, sd = 1)) +
  scale_color_manual(breaks = c("mean = 0, sd = 1", "mean = 0, sd = 3", 
                                "mean = -2, sd = 2", "mean = 2, sd = 1"),
                       values = colourvector[1:4])+
  scale_linetype_manual(breaks = c("mean = 0, sd = 1", "mean = 0, sd = 3", 
                                "mean = -2, sd = 2", "mean = 2, sd = 1"),
                        values = c("dashed", "solid", "twodash", "dotted"))+
  theme_minimal() + 
  labs(x = "values",
       y = "density",
       color = "Legend",
       linetype = "Legend")
```


# Uniform distribution
```{r}
ggplot(data.frame(x = c(-1, 4)), aes(x = x)) +
  stat_function(aes(colour = "min = 0, max = 1",
                    linetype = "min = 0, max = 1"),
                fun = dunif,
                args = list(min = 0, max = 1)) +
  stat_function(aes(colour = "min = 0, max = 2",
                    linetype = "min = 0, max = 2"),
                fun = dunif,
                args = list(min = 0, max = 2)) +
  stat_function(aes(colour = "min = 2, max = 3",
                    linetype = "min = 2, max = 3"),
                fun = dunif,
                args = list(min = 2, max = 3)) +
  scale_color_manual(breaks = c("min = 0, max = 1", "min = 0, max = 2", 
                                "min = 2, max = 3"),
                       values = colourvector[1:3])+
  scale_linetype_manual(breaks = c("min = 0, max = 1", "min = 0, max = 2", 
                                "min = 2, max = 3"),
                        values = c("dashed", "solid", "twodash"))+
  theme_minimal() + 
  labs(x = "values",
       y = "density",
       color = "Legend",
       linetype = "Legend")
```

# Cauchy distribution 
```{r}
ggplot(data.frame(x = c(-8, 8)), aes(x = x)) +
  stat_function(aes(colour = "location = 0, scale = 1",
                    linetype = "location = 0, scale = 1"),
                fun = dcauchy,
                args = list(location = 0, scale = 1)) +
  stat_function(aes(colour = "location = 0, scale = 3",
                    linetype = "location = 0, scale = 3"),
                fun = dcauchy,
                args = list(location = 0, scale = 3)) +
  stat_function(aes(colour = "location = 0, scale = 10",
                    linetype = "location = 0, scale = 10"),
                fun = dcauchy,
                args = list(location = 0, scale = 10)) +
  stat_function(aes(colour = "location = 1, scale = 2",
                    linetype = "location = 1, scale = 2"),
                fun = dcauchy,
                args = list(location = 1, scale = 2)) +
  scale_color_manual(breaks = c("location = 0, scale = 1", "location = 0, scale = 3",
                                "location = 0, scale = 10", "location = 1, scale = 2"),
                       values = colourvector[1:4])+
  scale_linetype_manual(breaks = c("location = 0, scale = 1", "location = 0, scale = 3",
                                   "location = 0, scale = 10", "location = 1, scale = 2"),
                        values = c("dashed", "solid", "twodash", "dotted"))+
  theme_minimal() + 
  labs(x = "values",
       y = "density",
       color = "Legend",
       linetype = "Legend")
```

# Exponential distribution
```{r}
ggplot(data.frame(x = c(-1, 1)), aes(x = x)) +
  stat_function(aes(colour = "rate = 0.1",
                    linetype = "rate = 0.1"),
                fun = dexp,
                args = list(rate = 0.1)) +
  stat_function(aes(colour = "rate = 1",
                    linetype = "rate = 1"),
                fun = dexp,
                args = list(rate = 1)) +
  stat_function(aes(colour = "rate = 2",
                    linetype = "rate = 2"),
                fun = dexp,
                args = list(rate = 2)) +
  stat_function(aes(colour = "rate = 5",
                    linetype = "rate = 5"),
                fun = dexp,
                args = list(rate = 5)) +
  scale_color_manual(breaks = c("rate = 0.1", "rate = 1", "rate = 2", "rate = 5"),
                       values = colourvector[1:4])+
  scale_linetype_manual(breaks = c("rate = 0.1", "rate = 1", "rate = 2", "rate = 5"),
                        values = c("dashed", "solid", "twodash", "dotted"))+
  theme_minimal() + 
  labs(x = "values",
       y = "density",
       color = "Legend",
       linetype = "Legend")
```

# Poisson distribution
```{r}
ggplot(data.frame(x = 0:4), aes(x = x)) +
  stat_function(aes(colour = "lambda = 0.1",
                    linetype = "lambda = 0.1"),
                n = length(0:4),
                fun = dpois,
                args = list(lambda = 0.1)) +
  stat_function(aes(colour = "lambda = 1",
                    linetype = "lambda = 1"),
                n = length(0:4),
                fun = dpois,
                args = list(lambda = 1)) +
  stat_function(aes(colour = "lambda = 2",
                    linetype = "lambda = 2"),
                n = length(0:4),
                fun = dpois,
                args = list(lambda = 2)) +
  stat_function(aes(colour = "lambda = 5",
                    linetype = "lambda = 5"),
                n = length(0:4),
                fun = dpois,
                args = list(lambda = 5)) +
  scale_color_manual(breaks = c("lambda = 0.1", "lambda = 1", "lambda = 2", "lambda = 5"),
                       values = colourvector[1:4])+
  scale_linetype_manual(breaks = c("lambda = 0.1", "lambda = 1", "lambda = 2", "lambda = 5"),
                        values = c("dashed", "solid", "twodash", "dotted"))+
  theme_minimal() + 
  labs(x = "values",
       y = "density",
       color = "Legend",
       linetype = "Legend")
```