---
title: "Bootstrap Testing"
author: "Koen Bresters"
date: "2023-02-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# import the monster function
source("monster_functie.r")

# define a nice plotting function
niceplot <- function(results, title, true_variance){
  variance_data = results
  hist(variance_data, xlab="estimated variance", main=title)
  mtext(paste("Mean Square Error = ", as.character(mean((variance_data-true_variance)^2))), side=4)
  abline(v=true_variance, col="red")
}

```

## normal dist with 0 mean parametric

```{r}
mean0norm <- function (sd){
  function(N){
    rnorm(N, mean=0, sd=sd)
  }
}

true_param = 1

results = param_monster(true_distr_gen=mean0norm, true_params=true_param, params_estimator=function(x) sd(x), n=100, N=1000, M=300)
true_variance = var(param_bootstrap_data(mean0norm(true_param), n=100, N=10000, estimator=function(x) sd(x)))
niceplot(results, "normal dist with mean 0 parametric results", true_variance)
```

## normal dist with unknown mean parametric

```{r}
normdist <- function (x){
  function(N){
    rnorm(N, mean=x$mean, sd=x$sd)
  }
}

full_estimator <- function(x) list(mean=mean(x), sd=sd(x))
estimator <- function(x) sd(x)
true_params = list(mean=0, sd=1)

results = param_monster(true_distr_gen=normdist, true_params=true_params, params_estimator=full_estimator, estimator=estimator, n=100, N=1000, M=300)
true_variance = var(param_bootstrap_data(normdist(true_params), n=100, N=10000, estimator=estimator))
niceplot(results, "normal dist with unknown mean parametric results", true_variance)
```

## normal dist non-parametric

```{r}
distr = normdist(list(mean=0, sd=1))
estimator = function(x) sd(x)
results = nonparam_monster(distr, estimator, n=100, M=300, N=1000)
true_variance = var(param_bootstrap_data(distr, n=100, N=10000, estimator=estimator))
niceplot(results, "normal dist non-parametric results", true_variance)
```
